-- ============================================================
-- TRPG テンプレート seed データ
-- ============================================================

INSERT INTO public.templates (
  id, label, description, sort_order,
  card_layout, web_layout, form_sections, orientation_scales,
  overlay_config, block_pool,
  card_width, card_height, web_width,
  card_config, sample_card_data
) VALUES (
  'trpg-v1',
  'TRPG 自己紹介カード',
  '遊ぶシステム・ロール・セッションスタイルを載せるTRPG向けカード',
  30,
  '{"gap":4,"flex":1,"type":"row","children":[{"gap":2,"minW":20,"type":"col","justify":"space-between","children":[{"minH":20,"type":"ref","blockId":"profileImage"},{"gap":1,"type":"col","children":[{"minH":3,"type":"ref","blockId":"x","bgVariant":"default"},{"minH":3,"type":"ref","blockId":"discord","bgVariant":"default"}]}]},{"gap":2,"minW":34,"type":"col","justify":"space-between","children":[{"minH":5,"type":"ref","blockId":"name","bgVariant":"default","contentFontScale":1.4},{"minH":6,"type":"ref","blockId":"systems","bgVariant":"default"},{"gap":2,"minH":3,"type":"row","children":[{"flex":1,"type":"ref","blockId":"trpgRole","bgVariant":"default","contentFontScale":0.9},{"flex":1,"type":"ref","blockId":"sessionStyle","bgVariant":"default","contentFontScale":0.9}]},{"gap":2,"minH":3,"type":"row","children":[{"flex":1,"type":"ref","blockId":"voiceStyle","bgVariant":"default","contentFontScale":0.9},{"flex":1,"type":"ref","blockId":"experience","bgVariant":"default","contentFontScale":0.9}]},{"minH":8,"type":"ref","blockId":"status","bgVariant":"default"}]},{"gap":2,"flex":1,"type":"col","children":[{"flex":1,"type":"ref","blockId":"selfIntro","bgVariant":"default","contentFontScale":0.75},{"minH":3,"type":"ref","blockId":"frequency","bgVariant":"default"}]}]}'::jsonb,
  '{"gap":3,"type":"col","children":[{"gap":3,"minH":20,"type":"row","children":[{"minW":26,"type":"ref","blockId":"profileImage"},{"gap":2,"flex":1,"type":"col","justify":"space-between","children":[{"minH":5,"type":"ref","blockId":"name","bgVariant":"default","contentFontScale":1.3},{"gap":1,"type":"col","children":[{"minH":3,"type":"ref","blockId":"x","bgVariant":"default"},{"minH":3,"type":"ref","blockId":"discord","bgVariant":"default"}]}]}]},{"type":"ref","blockId":"divider"},{"minH":6,"type":"ref","blockId":"systems","bgVariant":"default"},{"gap":2,"type":"row","children":[{"flex":1,"minH":4,"type":"ref","blockId":"trpgRole","bgVariant":"default"},{"flex":1,"minH":4,"type":"ref","blockId":"sessionStyle","bgVariant":"default"}]},{"gap":2,"type":"row","children":[{"flex":1,"minH":4,"type":"ref","blockId":"voiceStyle","bgVariant":"default"},{"flex":1,"minH":4,"type":"ref","blockId":"experience","bgVariant":"default"},{"flex":1,"minH":4,"type":"ref","blockId":"frequency","bgVariant":"default"}]},{"type":"ref","blockId":"divider"},{"minH":8,"type":"ref","blockId":"selfIntro","bgVariant":"default"},{"type":"ref","blockId":"divider"},{"minH":14,"type":"ref","blockId":"status","bgVariant":"default"}]}'::jsonb,
  '[{"items":[{"type":"font"},{"type":"block","dataKey":"background"}],"title":"カードデザイン","defaultOpen":true},{"items":[{"type":"block","dataKey":"profileImage","formLabel":"プロフィール画像"},{"type":"block","dataKey":"name","formLabel":"名前"},{"type":"block","dataKey":"selfIntro","formLabel":"自己紹介"}],"title":"プロフィール"},{"items":[{"type":"block","dataKey":"systems","formLabel":"遊ぶシステム"},{"type":"block","dataKey":"trpgRole","formLabel":"担当ロール"},{"type":"block","dataKey":"sessionStyle","formLabel":"セッションスタイル"},{"type":"block","dataKey":"voiceStyle","formLabel":"通話スタイル"},{"type":"block","dataKey":"experience","formLabel":"経験年数"},{"type":"block","dataKey":"frequency","formLabel":"活動頻度"}],"title":"TRPGスタイル"},{"items":[{"type":"block","dataKey":"status","formLabel":"ステータス"},{"type":"block","dataKey":"x","formLabel":"X ID"},{"type":"block","dataKey":"discord","formLabel":"Discord ID"}],"title":"ステータス・SNS"}]'::jsonb,
  '{"web":{"cardWidth":630,"cardHeight":900,"defaultPaddingScale":1.8,"defaultLabelFontScale":1.4,"defaultContentFontScale":1.4},"card":{}}'::jsonb,
  '{"inset":{"top":24,"left":32,"right":32,"bottom":24},"opacity":70,"variant":"glass","borderRadius":16,"innerPadding":20}'::jsonb,
  '{"x":{"dataKey":"x","variant":"default","blockConfig":{"platform":"x"},"componentKey":"simple-sns"},"name":{"label":"名前","dataKey":"name","variant":"default","subLabel":"handle name","blockConfig":{"multiline":false},"componentKey":"text"},"status":{"label":"ステータス","dataKey":"status","variant":"default","blockConfig":{"fields":[{"key":"blue","color":"#60a5fa","label":"募集中"},{"key":"green","color":"#4ade80","label":"セッション中"},{"key":"yellow","color":"#facc15","label":"調整中"},{"key":"red","color":"#f87171","label":"お休み中"}]},"componentKey":"color-status"},"discord":{"dataKey":"discord","variant":"default","blockConfig":{"platform":"discord"},"componentKey":"simple-sns"},"divider":{"dataKey":"divider","variant":"default","componentKey":"divider"},"systems":{"label":"遊ぶシステム","dataKey":"systems","variant":"default","subLabel":"systems","blockConfig":{"placeholder":"クトゥルフ、D&D、SW2.5…"},"componentKey":"tag-list"},"selfIntro":{"label":"自己紹介","dataKey":"selfIntro","variant":"default","subLabel":"about me","blockConfig":{"rows":4},"componentKey":"text"},"trpgRole":{"label":"ロール","dataKey":"trpgRole","variant":"slash","subLabel":"GM / PL","blockConfig":{"options":[{"label":"GM","value":"gm"},{"label":"PL","value":"pl"},{"label":"どちらも","value":"both"}]},"componentKey":"multi-select"},"background":{"dataKey":"background","componentKey":"background"},"experience":{"label":"経験年数","dataKey":"experience","variant":"default","subLabel":"experience","blockConfig":{"options":[{"label":"初心者","value":"beginner"},{"label":"1年未満","value":"lt1year"},{"label":"1〜3年","value":"1to3years"},{"label":"3〜5年","value":"3to5years"},{"label":"5年以上","value":"veteran"}]},"componentKey":"select"},"frequency":{"label":"活動頻度","dataKey":"frequency","variant":"default","subLabel":"frequency","blockConfig":{"options":[{"label":"週1以上","value":"weekly"},{"label":"月1〜2回","value":"monthly"},{"label":"不定期","value":"occasionally"}]},"componentKey":"select"},"voiceStyle":{"label":"通話","dataKey":"voiceStyle","variant":"slash","subLabel":"voice","blockConfig":{"options":[{"label":"ボイス","value":"voice"},{"label":"テキスト","value":"text"}]},"componentKey":"multi-select"},"profileImage":{"dataKey":"profileImage","variant":"default","componentKey":"profileImage"},"sessionStyle":{"label":"セッション","dataKey":"sessionStyle","variant":"slash","subLabel":"session","blockConfig":{"options":[{"label":"オンセ","value":"online"},{"label":"オフセ","value":"offline"},{"label":"どちらも","value":"both"}]},"componentKey":"multi-select"}}'::jsonb,
  900, 506, 630,
  '{"web":{"grid":{"gap":4,"cellSize":8},"autoHeight":true},"card":{"grid":{"gap":4,"cellSize":8}},"fontFamily":"sans-serif","overlayKey":"overlay","borderRadius":20,"backgroundKey":"background"}'::jsonb,
  '{"x":"","name":"","status":{},"discord":"","divider":null,"systems":[],"selfIntro":"","trpgRole":[],"background":null,"experience":"","frequency":"","voiceStyle":[],"profileImage":{"url":null,"base64":null},"sessionStyle":[]}'::jsonb
);

INSERT INTO public.community_templates (community_slug, template_id, sort_order) VALUES
  ('trpg', 'trpg-v1', 10);
